### PR TITLE
support no_std

### LINKED ISSUE #1: no_std support
It would be great to have `no_std` support. For us it would be acceptable to use `alloc`, as we're targeting Intel SGX enclaves.
This would help us resolving paritytech/substrate#5547

### PR DESCRIPTION
**Pull request by brenzi**
fixes #1

### CODE REVIEW

**Comment by vivekvpandya** [comment]
Could someone please merge this?

**Comment by vivekvpandya** [comment]
Can someone please merge this?

**Comment by brenzi** [comment]
@debris ?

**Comment by debris** [comment]
published in `0.2.0`

**Pull request merged**
